on: push
name: 'dockerhub-metadata build'
jobs:
  docker-hub-metadataIsMaster:
    name: docker-hub-metadata is master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-hub-metadata is master
      uses: actions/bin/filter@3c98a2679187369a2116d4f311568596d3725740
      with:
        args: branch master
    - name: docker-hub-metadata docker registry
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: build docker-hub-metadata
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: build -t mpepping/docker-hub-metadata-github-action ./docker-hub-metadata
    - name: push docker-hub-metadata
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push btamayo/docker-hub-metadata-github-action
