on:
  push:
    branches:    
      - master         # Push events on master branch
name: shellcheck docker build
jobs:
  shellcheckIsMaster:
    name: shellcheck is master
    runs-on: ubuntu-latest
    steps:
    - name: shellcheck docker registry
      uses: azure/container-actions/docker-login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: build shellcheck
      run: build -t btamayo/shellcheck-github-action ./shellcheck
    - name: push shellcheck
      run: push btamayo/shellcheck-github-action
