on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
name: pdk-validate docker build
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: pdk-validate docker registry
    uses: azure/container-actions/docker-login@master
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  - name: build pdk-validate
    run: docker build -t btamayo/pdk-validate-github-action
  - name: push pdk-validate
    run: docker push btamayo/pdk-validate-github-action