on:
  push:
    branches:    
      - master         # Push events on master branch
name: 'dockerhub-metadata build'
jobs:
  docker-hub-metadataIsMaster:
    name: docker-hub-metadata is master
    runs-on: ubuntu-latest
    steps:
    - name: docker-hub-metadata docker registry
      uses: azure/container-actions/docker-login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: build docker-hub-metadata
      run: build -t btamayo/docker-hub-metadata-github-action ./docker-hub-metadata
    - name: push docker-hub-metadata
      run: push btamayo/docker-hub-metadata-github-action
