on:
  push:
    branches:    
      - master         # Push events on master branch
name: 'dockerhub-metadata build'
jobs:
  docker-hub-metadataIsMaster:
    name: docker-hub-metadata is master
    runs-on: ubuntu-latest
    steps:
    - name: docker-hub-metadata docker registry
      uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build docker-hub-metadata
      run: docker build -t btamayo/docker-hub-metadata-github-action
    - name: push docker-hub-metadata
      run: docker push btamayo/docker-hub-metadata-github-action
