on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
name: pdk-validate docker build
jobs:
  runs-on: ubuntu-latest
  steps:
  - name: pdk-validate docker registry
    uses: azure/container-actions/docker-login@master
    env:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  - name: build pdk-validate
    run: build -t btamayo/pdk-validate-github-action ./pdk-validate
  - name: push pdk-validate
    run: push btamayo/pdk-validate-github-action